backend:
    name: github
    repo: albertpratomo/albertpratomo.github.io
    branch: master

publish_mode: editorial_workflow

media_folder: static/uploads
public_folder: /uploads

collections:
    - label: "Pages"
      name: "pages"
      files:
          - label: "Home"
            name: "home"
            file: "content/home.json"
            fields:
                - { label: Title, name: title, widget: string }
                - { label: Intro, name: intro, widget: markdown }
                - label: Works
                  name: works
                  widget: list
                  fields:
                      - { label: Company, name: company, widget: string }
                      - { label: Position, name: position, widget: string }
